### ISSUE TITLE
Incorrect URL

### ISSUE THREAD

**Issue by DavidPesticcio** [Ernyoke/certified-aws-sysops-associate#1]
Weblink in "About" points to:
`https://ervinszilagyi.site/certified-aws-sysops-associate`
instead of
`https://github.com/Ernyoke/certified-aws-sysops-associate`

**Comment by Ernyoke** [comment]
Thank you very much for reporting this issue.
I fixed it.

If you see any typos, corrections (anything unrelated to the the about ULR :) ), feel free to create a pull request.

Regards,
Ervin
